
# ---------------------------------------------------------------
# Basic  Settings
# ---------------------------------------------------------------

title: Visionary Lab
version: 1.0.0
subtitle:
description:
author: xta0
# support en, zh-Hans
language: zh-Hans
date_format: '%Y-%m-%d'

  # Put your favicon.ico into `assets/` directory.
favicon: /assets/favicon.ico
# Footer `powered-by` and `theme-info` copyright
copyright: true
# site url
url:
baseurl: 
permalink: pretty

# Pagination
# paginate: 10
# Handling Reading
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "README_en.md","bower_components","bower.json","package.json","node_modules"]

#Assets
sass:
  sass_dir: _sass
  style: :compressed

# markdown
highlighter: rouge
highlight:
  line_number: true

# ---------------------------------------------------------------
# Post  Settings
# ---------------------------------------------------------------

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true

# Post wordcount display settings
post_wordcount:
  item_text: true
  wordcount: false
  min2read: false
  separated_meta: true
  
  # Declare license on posts
post_copyright:
  enable: false
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/



###############################
# Menus
###############################
menu:
  home: /
  archives: /archives/
  about: /about/
  # tags: /tags/
  #sitemap: /sitemap.xml
  #commonweal: /404.html
menu_icons:
  enable: true
  home: home
  about: user
  categories: th
  schedule: calendar
  tags: tags
  archives: archive
  # sitemap: sitemap
  # commonweal: heartbeat

# ---------------------------------------------------------------
# 3rd partyl lib
# ---------------------------------------------------------------

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
    
# //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

vendors:
  # Internal path prefix. Please do not edit it.
  _internal: assets/lib

