
baseurl: 
markdown: kramdown
highlighter: none
kramdown:
   syntax_highlighter_opts:
      disable : true


# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true
  
# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

